---
demographics:
  census_fields:
  - field: name
    width: 18
    title: Name
  - field: ancestry
    width: 13
    title: Ancestry
  - field: heritage
    width: 16
    title: Heritage
  - field: charclass
    width: 13
    title: Class
  demographics:
  - full name
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - birthdate
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - gender
  - hair
  - physique
  genders:
    Male:
      possessive_pronoun: his
      subjective_pronoun: he
      objective_pronoun: him
      noun: man
    Female:
      possessive_pronoun: her
      subjective_pronoun: she
      objective_pronoun: her
      noun: woman
    Other:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: person
  groups:
    Region:
      desc: What region does your character call home?
      wiki: theme:region
      values:
        Am'shere: The distant jungles that were the ancestral homeland of the ciith, lost temporarily to time but back again.
        Bludgun: The land of Ten-Thousand Gods, also part of the Altiman Empire.
        Charn: The stygian domain of the Eastern Empire.
        The Desolation: Home of an endless magical storm, where the Illuminators now must make their camp.
        Dran: The Witchlands of Dran, known for powerful elementals, occult magics, and more.
        The Heartlands: Home to Alexandria, the Mythwood, and others.
        The Jade Islands: The remains of a shattered continent, populated by the Kaitoi and merchant circles.
        Khazad Duin: The ancestral homeland of the khazadi, known for its great mountains.
        Kimitatu: The floating islands of Kimitatu, devoted to the service of dragons.
        Myrddion: The kingdoms of Myrddion, also called the Western Empire.
        Periantha: The ancestral homeland of the sildanyari, now home to many in the border communities and the Kingdom of Llyranost.
        Rune: The eccentric city-state of Rune, known for the intense study of arcane magic.
        Skyhaldborg: The rugged north with a storied history of war.
        Tysmycha: The ancestral home of the kailli, known for great forests and hygienic protocols.
        Veyshan: Home of the desert nomads, the city-states of the One-Hundred and Four, and the Wolfrot Marshes.
    Faith:
      desc: World faith your character ascribes to first and foremost. (They may acknowledge and engage in other forms of faith.)
      wiki: theme:deity
      values:
        Adomism: The veneration of the strictures of Adom, the legendary hero of Bludgun.
        Black Iron Way: The harsh and strict faith of Charn, descended from the Holy Order of Ea.
        Caminara Toponi: The ancestral Kaitoi veneration of the volcano spirit Toponi and associated Kaitoi traditions.
        Green Word: The emerging faith of the Green Word, an environmental faith.
        Holy Order of Ea: The teachings of the descendant faiths of the Aiglosian Empire's religion.
        Holy Assembly: The Myrrish state temple, descended from the Holy Order of Ea.
        Skyhaldan Ancestor Worship: The veneration of ancestors in the Skyhaldan tradition.
        Ten-Thousand Gods: An animist belief from Bludgun that honors great spirits, ancient legends, and ancestors alike.
        Three Siblings: The Tysmychan veneration of the Three Siblings who founded Tysmycha.
        Zilvarel Union: The new faith rising in the Kingdom of Llyranost, claiming to resurrect an ancestral worship of Daeus as Eli.
        Other: You have your own ideas on the world and how it works, or you are a member of a more esoteric (and possibly secret) tradition or smaller tradition.
  help_text:
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <ea_month> <day> <year>%xn%r%t%xcbirthdate <rl_month> <day> <year>%xn%r%t%xcbirthday <MM>/<DD>/<YYYY>%xc%r%tor %xcage <years>%cn, - Set your character's birthday or age. See the Calendar of Ea page on the wiki for the Ea months.%xn"
    full name: "%xcfullname <name>%xn - Your character's full name."
  max_age: 1000
  min_age: 18
  nickname_field: ''
  nickname_format: "%{name} (%{nickname})"
  permissions:
    manage_demographics: Edit demographics on other players.
  private_properties: []
  required_properties:
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    demographics: demographic
    birthday: birthdate
    fullname: demographic/set full name=
    faith: group/set faith=
    region: group/set region=
    faith/info: group faith
    region/info: group region
