---
pf2e_ancestry:
  Arvek:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Yrch
    traits:
      - arvek
      - humanoid
    special:
      - darkvision
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Dar
      - Ghaluch
      - Niasa
      - Manabane
      - Runtboss
      - Shortshanks
      - Silyara
      - Smokeworker
      - Warmarch
      - Warrenbred
    feats:
      1:
        - Alchemical Scholar
        - Arvek Lore
        - Arvek Weapon Familiarity
        - Cantorian Reinforcement 
        - Leech-Clip
        - Remorseless Lash
        - Sneaky
        - Stone Face
        - Vigorous Health
      5:
        - Agonizing Rebuke
        - Expert Drill Sergeant
        - Recognize Ambush
        - Runtsage
      9:
        - Cantorian Rejuvenation
        - Fell Rider
        - Pride in Arms
        - Squad Tactics
      13:
        - Can't Fall Here
        - War Conditioning
      17:
        - Cantorian Restoration
        - Rallying Cry
    adopted_feats:
      - Alchemical Scholar
      - Arvek Lore
      - Arvek Weapon Familiarity
      - Leech-Clip
      - Remorseless Lash
      - Sneaky
      - Stone Face
      - Agonizing Rebuke
      - Expert Drill Sergeant
      - Recognize Ambush
      - Fell Rider
      - Pride in Arms
      - Squad Tactics
      - Can't Fall Here
      - War Conditioning
      - Rallying Cry
  Bassin:
    HP: 6
    Size: S
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Bassini
    traits:
      - bassin
      - humanoid
    special:
      - keen eyes
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Dar
      - Ghaluch
      - Gutsy
      - Hillock
      - Jinxed-bassin
      - Niasa
      - Nomadic
      - Silyara
      - Twilight
      - Wildwood
    feats:
      1:
        - Bassin Lore
        - Bassin Luck
        - Bassin Weapon Familiarity
        - Distracting Shadows
        - Folksy Patter
        - Prairie Rider
        - Sure Feet
        - Titan Slinger
        - Unfettered Bassin
        - Watchful Bassin
      5:
        - Cultural Adaptability
        - Step Lively
      9:
        - Dance Underfoot
        - Guiding Luck
        - Irrepressible (Bassin)
        - Unhampered Passage
      13:
        - Ceaseless Shadows
        - Toppling Dance
      17:
        - Shadow Self
    adopted_feats:
      - Bassin Lore
      - Bassin Weapon Familiarity
      - Folksy Patter
      - Prairie Rider
      - Titan Slinger
      - Unfettered Bassin
      - Watchful Bassin
      - Irrepressible (Bassin)
      - Unhampered Passage
      - Shadow Self
  Ciith:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Am'sheran Draconic
    traits:
      - ciith
      - humanoid
    attack:
      Claw:
        damage: 1d4
        damage_type: S
        group: Brawling
        traits:
          - agile
          - finesse
          - unarmed
    bonus_feats:
      - Breath Control
    heritages:
      - Aesa
      - Ahcan
      - Ashen One
      - Changeling
      - Dar
      - Makar
      - Niasa
      - Otocami
      - Paeezh
      - Pantli
      - Xalli
    feats:
      1:
        - Bone Magic
        - Ciith Armaments
        - Ciith Lore
        - Marsh Runner
        - Parthenogenic Hatchling
        - Reptile Speaker
      5:
        - Envenom Fangs
        - Flexible Tail
        - Gecko's Grip
        - Shed Tail
        - Swift Swimmer
      9:
        - Dangle
        - Hone Claws
        - Terrain Advantage
      13:
        - Bone Investiture
        - Ciith Spirit Strike 
        - Primal Rampage
      17:
        - Fossil Rider 
        - Scion Transformation
    adopted_feats:
      - Bone Magic
      - Ciith Lore
      - Reptile Speaker
      - Terrain Advantage
      - Bone Investiture
      - Primal Rampage
      - Fossil Rider
  Egalrin:
    HP: 6
    Size: M
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Kaminean
    traits:
      - egalrin
      - humanoid
    special:
      - Low-Light Vision
    attack:
      Beak:
        damage: 1d6
        damage_type: P
        group: Brawling
        traits:
          - finesse
          - unarmed
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Dar
      - Dogtooth
      - Jinxed-egalrin
      - Mountainkeeper
      - Niasa    
      - Skyborn
      - Stormtossed
      - Taloned
      - Wavediver
    feats:
      1:
        - Egalrin Lore
        - Egalrin Weapon Familiarity
        - Mariner's Fire
        - One-Toed Hop
        - Scavenger's Search
        - Squawk!
        - Storm's Lash
        - Uncanny Agility
      5:
        - Eat Fortune
        - Egalrin Feather Fan
        - Long-Nosed Form
        - Magpie Snatch
        - Soaring Flight
      9:
        - Soaring Form
        - Wind God's Fan
      13:
        - Harbinger's Caw
        - Jinx Glutton
        - Thunder God's Fan
      17:
        - Great Egalrin Form
        - Trickster Egalrin
    adopted_feats:
      - Egalrin Lore
      - Egalrin Weapon Familiarity
      - Mariner's Fire
      - Scavenger's Search
      - Squawk!
      - Storm's Lash
      - Uncanny Agility
      - Magpie Snatch
      - Harbinger's Caw
      - Trickster Egalrin
  Goblin:
    HP: 6
    Size: S
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Goblin
    traits:
      - goblin
      - humanoid
    special:
      - darkvision
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Charhide
      - Dar
      - Ghaluch
      - Irongut
      - Niasa
      - Razortooth
      - Silyara
      - Snow
      - Unbreakable
    feats:
      1:
        - Burn It!
        - City Scavenger
        - Goblin Lore
        - Goblin Scuttle
        - Goblin Song
        - Goblin Weapon Familiarity
        - Rough Rider
        - Very Sneaky
      5:
        - Kneecap
        - Loud Singer
        - Vandal
      9:
        - Cave Climber
        - Cling
        - Skittering Scuttle
      13:
        - Very, Very Sneaky
      17:
        - Reckless Abandon
    adopted_feats:
      - Burn It!
      - City Scavenger
      - Goblin Lore
      - Goblin Scuttle
      - Goblin Song
      - Goblin Weapon Familiarity
      - Rough Rider
      - Very Sneaky
      - Kneecap
      - Loud Singer
      - Vandal
      - Cave Climber
      - Skittering Scuttle
      - Very, Very Sneaky
      - Reckless Abandon
  Gnome:
    HP: 8
    Size: S
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Gnomish
      - Sylhart
    traits:
      - gnome
      - humanoid
    special:
      - Low-Light Vision
    heritages:
      - Aesa
      - Ashen One
      - Chameleon
      - Changeling
      - Dar
      - Fey-Touched
      - Ghaluch
      - Niasa
      - Sensate
      - Silyara
      - Umbral
      - Wellspring (Arcane)
      - Wellspring (Divine)
      - Wellspring (Occult)
    feats:
      1:
        - Animal Accomplice
        - Animal Elocutionist
        - Fey Fellowship
        - Gnome Obsession
        - Gnome Weapon Familiarity
        - Illusion Sense
        - Quelynos Magic
        - Razzle-Dazzle
      5:
        - Energized Font
        - Project Persona
      9:
        - Cautious Curiosity
        - Life Leap
        - Quelynos Adept
        - Vivacious Conduit
      13:
        - Instinctive Obfuscation
      17:
        - Homeward Bound
    adopted_feats:
      - Animal Accomplice
      - Animal Elocutionist
      - Gnome Obsession
      - Gnome Weapon Familiarity
      - Razzle-Dazzle
      - Project Persona
  Human:
    HP: 8
    Size: M
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
    bonus_languages: 1
    traits:
      - human
      - humanoid
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Dar
      - Ghaluch
      - Niasa
      - Silyara
      - Skilled
      - Versatile
    feats:
      1:
        - Adapted Cantrip
        - Cooperative Nature
        - General Training
        - Haughty Obstinacy
        - Natural Ambition
        - Natural Skill
        - Unconventional Weaponry
      5:
        - Adaptive Adept
        - Clever Improviser
        - Sense Allies
      9:
        - Cooperative Soul
        - Group Aid
        - Hardy Traveler
        - Incredible Improvisation
        - Multitalented
      13:
        - Advanced General Training
        - Bounce Back
        - Stubborn Persistence
      17:
        - Heroic Presence
    adopted_feats:
      - Adapted Cantrip
      - General Training
      - Natural Ambition
      - Natural Skill
      - Adaptive Adept
      - Clever Improviser
      - Sense Allies
      - Group Aid
      - Hardy Traveler
      - Multitalented
      - Advanced General Training
  Kailli:
    HP: 6
    Size: S
    Speed: 25
    attack:
      Jaws:
        damage: 1d4
        damage_type: P
        group: Brawling
        traits:
          - agile
          - finesse
          - unarmed
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Kaillin
    traits:
      - humanoid
      - kailli
    special:
      - Low-Light Vision
    heritages:
      - Aesa
      - Ashen One
      - Changeling
      - Dar
      - Deep Kailli
      - Desert Kailli
      - Longsnout Kailli
      - Niasa
      - Sewer Kailli
      - Shadow Kailli
      - Tunnel Kailli
      - Snow Kailli
    feats:
      1:
        - Cheek Pouches
        - Kailli Lore
        - Pack Rat
        - Rat Familiar
        - Ratspeak
        - Tinkering Fingers
        - Vicious Incisors
        - Warren Navigator
      5:
        - Cornered Fury
        - Kailli Roll
        - Lab Rat
        - Quick Stow (Kailli)
        - Rat Magic
      9:
        - Big Mouth
        - Overcrowd
        - Rat Form
        - Uncanny Cheeks
      13:
        - Shinstabber
        - Skittering Sneak
        - Warren Digger
      17:
        - Call the Swarm
        - Greater than the Sum
    adopted_feats:
      - Kailli Lore
      - Pack Rat
      - Rat Familiar
      - Ratspeak
      - Tinkering Fingers
      - Warren Navigator
      - Cornered Fury
      - Lab Rat
      - Rat Magic
      - Skittering Sneak
      - Call the Swarm
      - Greater than the Sum
  Khazad:
    HP: 10
    Size: M
    Speed: 20
    abl_boosts:
      - open
      - open
    languages:
      - Khazdul
      - Kamin
    traits:
      - khazad
      - humanoid
    special:
      - Darkvision
    heritages:
      - Aesa
      - Ancient-Blooded
      - Ashen One
      - Changeling
      - Dar
      - Death Warden
      - Forge
      - Ghaluch
      - Niasa
      - Rock
      - Silyara
      - Strong-Blooded
    feats:
      1:
        - Khazadi Doughtiness
        - Khazadi Lore
        - Khazadi Weapon Familiarity
        - Rock Runner
        - Stonemason's Eye
        - Unburdened Iron
      5:
        - Boulder Roll
        - Defy the Darkness
        - Khazadi Reinforcement
      9:
        - Echoes in Stone
        - Mountain's Stoutness
        - Stone Bones
        - Stonewalker
      13:
        - March the Mines
        - Telluric Power
      17:
        - Stonegate
        - Stonewall
    adopted_feats:
      - Khazadi Doughtiness
      - Khazadi Lore
      - Khazadi Weapon Familiarity
      - Stonemason's Eye
      - Unburdened Iron
      - Defy the Darkness
      - Khazadi Reinforcement
      - Stonewalker
      - Stonegate
  Oruch:
    HP: 10
    Size: M
    Speed: 25
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Yrch
    traits:
      - oruch
      - humanoid
    special:
      - darkvision
    heritages:
      - Aesa
      - Ashen One
      - Battle-ready
      - Badlands
      - Changeling
      - Dar
      - Deep Oruch
      - Grave
      - Hold-Scarred
      - Niasa
      - Silyara
      - Rainfall
      - Winter
    feats:
      1:
        - Beast Trainer
        - Iron Fists
        - Oruch Ferocity
        - Oruch Lore
        - Oruch Superstition
        - Oruch Weapon Familiarity
        - Tusks (Oruch)
      5:
        - Athletic Might
        - Bloody Blows
        - Defy Death
        - Scar-Thick Skin
      9:
        - Pervasive Superstition
        - Undying Ferocity
      13:
        - Ferocious Beasts
        - Incredible Ferocity
        - Spell Devourer
      17:
        - Rampaging Ferocity
    adopted_feats:
      - Beast Trainer
      - Oruch Lore
      - Oruch Superstition
      - Oruch Weapon Familiarity
      - Athletic Might
      - Bloody Blows
      - Scar-Thick Skin
      - Pervasive Superstition
      - Spell Devourer
  Sildanyar:
    HP: 6
    Size: M
    Speed: 30
    abl_boosts:
      - open
      - open
    languages:
      - Kamin
      - Silya
    traits:
      - sildanyar
      - humanoid
    special:
      - Low-Light Vision
    heritages:
      - Aesa
      - Ashen One
      - Arctic
      - Cavern
      - Changeling
      - Dar
      - Ghaluch
      - Niasa
      - Seer
      - Whisper
      - Woodland
    feats:
      1:
        - Ancestral Longevity
        - Forlorn
        - Nimble Sil
        - Otherworldly Magic
        - Sildanyari Lore
        - Sildanyari Weapon Familiarity
        - Unwavering Mien
      5:
        - Ageless Patience
        - Ancestral Suspicion
      9:
        - Expert Longevity
        - Otherworldly Acumen
        - Sildanyar Step
        - Tree Climber (Sildanyar)
      13:
        - Avenge Ally
        - Universal Longevity
      17:
        - Magic Rider
    adopted_feats:
      - Ancestral Longevity
      - Sildanyari Lore
      - Sildanyari Weapon Familiarity
      - Unwavering Mien
      - Expert Longevity
      - Sildanyar Step
      - Tree Climber (Sildanyar)
      - Avenge Ally
      - Universal Longevity
