---
pf2e:
  achievements:
    dungeon_keeper:
      type: community
      message: Ran %{count} Player-Run Plots.
      levels:
      - 1
      - 10
      - 25
      - 50
      - 100
      - 250
      - 500
    master_of_meetups:
      type: community
      message: Ran %{count} Meetups.
      levels:
      - 1
      - 10
      - 25
      - 50
      - 100
      - 250
      - 500
  shortcuts:
    sheet/top: sheet/info
    rollalias: roll/alias
    remalias: roll/alias
    listalias: roll/listalias
    rollfor: roll/for
    csheet: sheet/combat
    formulalist: formulas/list
    boog: boost # Just for Whirlpool
    init: encounter/join
    tinit: encounter/view
    pinit: encounter/prev
    ninit: encounter/next
    rminit: encounter/remove
    tscan: encounter/scan
    jinit: encounter/add
    modinit: encounter/mod
    resume: encounter/end
  allowed_alignments:
  - LG
  - NG
  - CG
  - LN
  - N
  - CN
  roll_channel: 'Rolls'
  can_select_language:
  - common
  - uncommon
  open_sheets: true
  open_npc_sheets: false
  title_color: '%x172'
  list_item: '%x229'
  use_alignment: true
  use_untrained_improv: false
  subclass_names:
    Alchemist: 'Research Field'
    Barbarian: 'Instinct'
    Bard: 'Muse'
    Champion: 'Cause'
    Druid: 'Order'
    Ranger: "Hunter's Edge"
    Rogue: 'Racket'
    Sorcerer: 'Bloodline'
    Wizard: 'Thesis'
    Investigator: 'Methodology'
    Oracle: 'Mystery'
    Witch: 'Patron'
  condition_colors:
    Dying: '%xr'
    Wounded: '%xy'
    Drained: '%xh%xx'
    Doomed: '%x172'
  hidden_options:
  - Fey Bullshit Lore
  permissions:
    modify_sheet: Modify character sheets.
    view_sheets: View other people's character sheets (if sheets are closed).
    kill_pc: (Associated to DM role) Has the ability to inflict Drained, Doomed, and Dead conditions on PC's.
  basic_mc_feats:
  - Basic Concoction 
  - Basic Fury
  - Basic Muse's Whispers
  - Basic Devotion
  - Basic Dogma
  - Basic Wilding
  - Basic Maneuver
  - Basic Deduction
  - Basic Kata
  - Basic Mysteries
  - Basic Hunter's Trick
  - Basic Trickery
  - Basic Blood Potency
  - Basic Witchcraft
  - Basic Arcana
  adv_mc_feats:
  - Advanced Concoction
  - Advanced Fury
  - Advanced Muse's Whispers
  - Advanced Devotion
  - Advanced Dogma
  - Advanced Wilding
  - Advanced Maneuver
  - Advanced Deduction 
  - Advanced Kata
  - Advanced Mysteries
  - Advanced Hunter's Trick
  - Advanced Trickery
  - Advanced Blood Potency
  - Advanced Witchcraft
  - Advanced Arcana
  valid_feat_types:
  - ancestry
  - charclass
  - skill
  - general
  - archetype
  - dedication
  daily_prep_cron:
    hour: 
    - 10
    minute:
    - 03
