---
pf2e_heritage:
  # Arvek Heritages
  Manabane:
    reaction:
      - Resist Magic
    action: []
    defense: {}
    feat: []
    skills: []
    special: []
    traits: []
    attack: {}
  Runtboss:
    feat:
      - Group Coercion
    special:
      - Runtboss Arvek
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    traits: []
  Shortshanks:
    action: []
    attack: {}
    defense: {}
    feat:
      - Ride
    reaction: []
    skills: []
    special:
      - Shortshanks Arvek
    traits: []
  Smokeworker:
    defense:
      resistances:
        fire: 1
    special:
      - Smokeworker Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Warmarch:
    special:
      - Warmarch Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Warrenbred:
    special:
      - Warrenbred Arvek
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  # Bassin Heritages
  Gutsy:
    special:
      - Gutsy Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Hillock:
    rest_HP_bonus: true
    special:
      - Hillock Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Jinxed-bassin:
    special:
      - Jinxed Bassin
    action:
      - Jinx
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Nomadic:
    language:
      - open
      - open
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Twilight:
    special:
      - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Wildwood:
    special:
      - Wildwood Bassin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  # Ciith Heritage Feats
  Ahcan:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Makar:
    movement:
      Swim: 15
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Otocami:
    action: []
    attack: {}
    defense: {}
    feat:
      - Terrain Stalker
    reaction: []
    skills: []
    special:
      - Otocami Ciith
    traits: []
  Pantli:
    feat:
      - Combat Climber
    special:
      - Pantli Ciith
    traits: []
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Paeezh:
    special:
      - Paeezh Ciith
    action:
      - Threatening Approach
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Xalli:
    defense:
      resistances:
        fire: 1
    special:
      - Xalli Ciith
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  # Egalrin Heritages
  Dogtooth:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special:
      - Dogtooth Egalrin
    traits: []
  Jinxed-egalrin:
    special:
      - Jinxed Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Mountainkeeper:
    magic_stats:
      innate_spell:
        level: cantrip
        name: Disrupt Undead
        tradition: primal
        cast_stat: Charisma
    special:
      - Mountainkeeper Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Skyborn:
    special:
      - Skyborn Egalrin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Stormtossed:
    defense:
      resistances:
        electricity: 1
    special:
      - Stormtossed Egalrin
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Taloned:
    attack:
      Talons:
        damage: 1d4
        damage_type: S
        traits:
          - agile
          - finesse
          - unarmed
          - versatile piercing
    action: []
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Wavediver:
    movement:
      Swim: 15
    special: []
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  # Gnome Heritages
  Chameleon:
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Fey-Touched:
    traits:
      - fey
    magic_stats:
      innate_spell:
        level: cantrip
        name: open
        tradition: arcane
        cast_stat: Charisma
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
  Sensate:
    special:
      - imprecise scent
      - Sensate Gnome
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Umbral:
    special:
      - Darkvision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Wellspring (Arcane):
    magic_stats:
      innate_spell:
        level: cantrip
        name: open
        tradition: arcane
        cast_stat: Charisma
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Wellspring (Divine):
    magic_stats:
      innate_spell:
        level: cantrip
        name: open
        tradition: divine
        cast_stat: Charisma
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Wellspring (Occult):
    magic_stats:
      innate_spell:
        level: cantrip
        name: open
        tradition: occult
        cast_stat: Charisma
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  # Goblin Heritages
  Charhide:
    defense:
      resistances:
        fire: 1
    special:
      - Charhide Goblin
    traits: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Irongut:
    special:
      - Irongut Goblin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  Razortooth:
    attack:
      Jaws:
        damage: 1d6
        damage_type: P
        group: brawling
        traits:
          - finesse
          - unarmed
    action: []
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Snow:
    defense:
      resistances:
        cold: 1
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Unbreakable:
    ancestry_HP: 10
    special:
      - Unbreakable Goblin
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    traits: []
  # Human Heritages
  Skilled:
    skills:
      - open
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    special: []
    traits: []
  Versatile:
    feat: []
    choose_feat:
      - general
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    special: []
    traits: []
  # Kailli Heritages
  Deep Kailli:
    traits: []
    special:
      - Darkvision
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Desert Kailli:
    defense: {}
    traits: []
    special: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Longsnout Kailli:
    traits: []
    special:
      - Scent (imprecise)
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Sewer Kailli:
    traits: []
    special:
      - Sewer Kailli
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Shadow Kailli:
    traits: []
    special:
      - Shadow Kailli
    skills:
      - Intimidation
    feat: []
    action: []
    reaction: []
    attack: {}
  Tunnel Kailli:
    traits: []
    special:
      - Tunnel Kailli
    skills: []
    feat:
      - Quick Squeeze
    action: []
    reaction: []
    attack: {}
  Snow Kailli:
    defense:
      resistances:
        cold: 1
    traits: []
    special:
      - Snow Kailli
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  # Khazad Heritages
  Ancient-Blooded:
    reaction: Call On Ancient Blood
    action: []
    attack: {}
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
  Death Warden:
    traits: []
    special: []
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Forge:
    defense:
      resistances:
        fire: 1
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Rock:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Strong-Blooded:
    defense:
      resistances:
        poison: 1
    action: []
    attack: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  # Oruch Heritages
  Battle-ready:
    traits: []
    special: []
    skills:
      - Intimidation
    feat:
      - Intimidating Glare
    defense: {}
    action: []
    reaction: []
    attack: {}
  Badlands:
    traits: []
    special:
      - Badlands Oruch
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Deep Oruch:
    feat:
      - Terrain Expertise/Underground
      - Combat Climber
    traits: []
    special: []
    skills: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Grave:
    traits: []
    special:
      - Grave Oruch
    skills: []
    feat: []
    defense:
      resistances:
        void: 1
    action: []
    reaction: []
    attack: {}
  Hold-Scarred:
    ancestry_HP: 12
    feat:
      - Diehard
    action: []
    attack: {}
    defense: {}
    reaction: []
    skills: []
    special: []
    traits: []
  Rainfall:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Winter:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits:
      - Winter Oruch
  # Sildanyar Heritages
  Arctic:
    traits: []
    defense:
      resistances:
        cold: 1
    circumstance: true
    special: []
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Cavern:
    traits: []
    special:
      - Darkvision
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Seer:
    magic_stats:
      innate_spell:
        level: 1
        name: Detect Magic
        tradition: arcane
        cast_stat: Charisma
    action: {}
    action_bonus: 1
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Whisper:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  Woodland:
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
    special: []
    traits: []
  # Limited Heritages
  Ghaluch:
    traits:
      - oruch
      - ghaluch
    special:
      - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
  Silyara:
    traits:
      - silyara
      - sildanyar
    special:
      - Low-Light Vision
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []
  # Versatile Heritages
  Aesa:
    rare: true
    traits:
      - aesa
    special:
      - Low-Light Vision
    change_vision: true
    action: []
    attack: {}
    reaction: []
    skills: []
    feat: []
    defense: {}
  Ashen One:
    rare: true
    traits:
      - ashen one
    special:
      - Low-Light Vision
    defense: {}
    change_vision: true
    skills: []
    feat: []
    action: []
    reaction: []
    attack: {}
  Changeling:
    rare: true
    traits:
      - changeling
    special:
      - Low-Light Vision
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
    change_vision: true
  Dar:
    rare: true
    traits:
      - dar
    special:
      - Low-Light Vision
      - Negative Healing
    change_vision: true
    skills: []
    feat: []
    defense: {}
    action: []
    reaction: []
    attack: {}
  Niasa:
    rare: true
    traits:
      - niasa
    special:
      - Low-Light Vision
    change_vision: true
    action: []
    attack: {}
    defense: {}
    feat: []
    reaction: []
    skills: []