---
pf2e_armor:
  Breastplate:
    category: medium
    traits: []
    level: 0
    price: 800
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -2
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Plate
  Chain Mail:
    category: medium
    traits:
      - flexible
      - noisy
    level: 0
    price: 600
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -2
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Chain
  Chain Shirt:
    category: light
    traits:
      - flexible
      - noisy
    level: 0
    price: 500
    ac_bonus: 2
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 12
    bulk: 1
    group: Chain
  Dragonplate (Avarice):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Bestial):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Brine):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Cloud):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Crystal):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Diabolic):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Empyreal):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Forest):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Fortune):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Madness):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Magma):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Mirage):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Ossuary):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Terra):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Dragonplate (Umbral):
    category: heavy
    traits:
      - uncommon
      - bulwark
      - invested
      - magical
    level: 16
    price: 1000000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2
  Electric Eelskin:
    category: light
    traits:
      - invested
      - magical
    level: 10
    price: 95000
    ac_bonus: 1
    dex_cap: 4
    check_penalty: 0
    speed_penalty: 0
    min_str: 10
    bulk: 1
    group: Leather
    runes:
      fundamental:
        potency: 1
        power: 1
      property:
        - Slick (Greater)
  Explorer's Clothing:
    category: unarmored
    traits:
      - comfort
    level: 0
    price: 10
    ac_bonus: 0
    dex_cap: 5
    check_penalty: 0
    speed_penalty: 0
    min_str: 0
    bulk: 0.1
    group: Cloth
  Full Plate:
    category: heavy
    traits:
      - bulwark
    level: 2
    price: 3000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
  Ghoul Hide:
    category: medium
    traits:
      - uncommon
      - invested
      - magical
    level: 6
    price: 22000
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: 0
    min_str: 14
    bulk: 2
    group: Leather
    runes:
      fundamental:
        potency: 1
  Half Plate:
    category: heavy
    traits: []
    level: 1
    price: 1800
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Plate
  Hide:
    category: medium
    traits: []
    level: 0
    price: 200
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: -5
    min_str: 14
    bulk: 2
    group: Leather
  Holy Chain:
    category: medium
    traits:
      - divine
      - holy
      - invested
      - noisy
    level: 13
    price: 250000
    ac_bonus: 4
    dex_cap: 1
    check_penalty: 0
    speed_penalty: 0
    min_str: 16
    bulk: 1
    group: Chain
    runes:
      fundamental:
        potency: 2
        power: 1
  Impenetrable Scale:
    category: medium
    traits:
      - uncommon
      - invested
      - magical
    level: 17
    price: 1280000
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: -5
    min_str: 14
    bulk: 3
    group: Composite
    runes:
      fundamental:
        potency: 2
        power: 2
      property:
        - Fortification
  Leather:
    category: light
    traits: []
    level: 0
    price: 200
    ac_bonus: 1
    dex_cap: 4
    check_penalty: -1
    speed_penalty: 0
    min_str: 10
    bulk: 1
    group: Leather
  Life-Saver Mail:
    category: heavy
    traits:
      - magical
    level: 14
    price: 400000
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Composite
    runes:
      fundamental:
        potency: 2
        power: 1
      property:
        - Fortification
  Life-Saver Mail (Greater):
    category: heavy
    traits:
      - magical
    level: 20
    price: 5250000
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Composite
    runes:
      fundamental:
        potency: 3
        power: 2
      property:
        - Fortification (Greater)
  Lion's Armor:
    category: heavy
    traits:
      - invested
      - magical
    level: 12
    price: 200000
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 0
    group: Plate
    bonus:
      Intimidation: 2
    runes:
      fundamental:
        potency: 2
        power: 1
  Lion's Armor (Greater):
    category: heavy
    traits:
      - invested
      - magical
    level: 19
    price: 3050000
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 0
    group: Plate
    bonus:
      Intimidation: 3
    runes:
      fundamental:
        potency: 3
        power: 2
  Mariner's Splint:
    category: heavy
    traits:
      - uncommon
      - invested
      - magical
    level: 5
    price: 18000
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Composite
    runes:
      fundamental:
        potency: 1
  Moonlit Chain:
    category: light
    traits:
      - flexible
      - invested
      - magical
      - noisy
    level: 7
    price: 36000
    ac_bonus: 2
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 12
    bulk: 1
    group: Chain
    runes:
      fundamental:
        potency: 1
  Onslaught Hide:
    category: medium
    traits:
      - invested
      - magical
    level: 9
    price: 70000
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -1
    speed_penalty: 0
    min_str: 14
    bulk: 2
    group: Leather
    runes:
      fundamental:
        potency: 1
        power: 1
  Padded:
    category: light
    traits:
      - comfort
    level: 0
    price: 20
    ac_bonus: 1
    dex_cap: 3
    check_penalty: 0
    speed_penalty: 0
    min_str: 10
    bulk: 0.1
    group: Cloth
  Scale Mail:
    category: medium
    traits: []
    level: 0
    price: 400
    ac_bonus: 3
    dex_cap: 2
    check_penalty: -2
    speed_penalty: -5
    min_str: 14
    bulk: 2
    group: Composite
  Splint Mail:
    category: heavy
    traits: []
    level: 1
    price: 1300
    ac_bonus: 5
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -10
    min_str: 16
    bulk: 3
    group: Composite
  Studded Leather:
    category: light
    traits: []
    level: 0
    price: 300
    ac_bonus: 2
    dex_cap: 3
    check_penalty: -1
    speed_penalty: 0
    min_str: 12
    bulk: 1
    group: Leather
  Tideplate:
    category: heavy
    traits: []
    level: 10
    price: 100000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 1
        power: 1
  Unholy Plate:
    category: heavy
    traits:
      - bulwark
      - divine
      - invested
      - unholy
    level: 13
    price: 250000
    ac_bonus: 6
    dex_cap: 0
    check_penalty: -3
    speed_penalty: -10
    min_str: 18
    bulk: 4
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 1
  Warleader's Bulwark:
    category: medium
    traits:
      - invested
      - magical
    level: 10
    price: 100000
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -2
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Plate
    runes:
      fundamental:
        potency: 1
        power: 1
  Warleader's Bulwark (Greater):
    category: medium
    traits:
      - invested
      - magical
    level: 18
    price: 2200000
    ac_bonus: 4
    dex_cap: 1
    check_penalty: -3
    speed_penalty: -5
    min_str: 16
    bulk: 2
    group: Plate
    runes:
      fundamental:
        potency: 2
        power: 2