---
pf2e_shields:
  Buckler:
    ac_bonus: 1
    bulk: 0.1
    hardness: 3
    hp: 6
    level: 0
    price: 100
    speed_penalty: 0
    traits: []
  Dragonslayer's Shield (Avarice):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Bestial):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Brine):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Cloud):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Crystal):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Diabolic):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Empyreal):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Forest):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Fortune):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Madness):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Magma):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Mirage):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Ossuary):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Terra):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Dragonslayer's Shield (Umbral):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 32
    level: 9
    price: 67000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Exploding Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 3
    hp: 12
    level: 5
    price: 2500
    speed_penalty: 0
    traits:
      - magical
  Floating Shield:
    ac_bonus: 1
    bulk: 0.1
    hardness: 6
    hp: 24
    level: 11
    price: 125000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Floating Shield (Greater):
    ac_bonus: 1
    bulk: 0.1
    hardness: 6
    hp: 24
    level: 16
    price: 900000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Force Shield:
    ac_bonus: 2
    bulk: 0.1
    hardness: 8
    hp: 32
    level: 9
    price: 65000
    speed_penalty: 0
    traits:
      - uncommon
      - force
      - magical
  Forge Warden:
    ac_bonus: 2
    bulk: 1
    hardness: 10
    hp: 40
    level: 10
    price: 97500
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Glamorous Buckler:
    ac_bonus: 1
    bulk: 0.1
    hardness: 3
    hp: 6
    level: 2
    price: 3500
    speed_penalty: 0
    traits:
      - magical
  Indestructible Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 17
    hp: 136
    level: 18
    price: 2400000
    speed_penalty: 0
    traits:
      - rare
      - magical
  Lion's Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 6
    hp: 36
    level: 6
    price: 24500
    speed_penalty: 0
    traits:
      - magical
  Lodestone Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 10
    hp: 92
    level: 11
    price: 135000
    speed_penalty: 0
    traits:
      - magical
  Martyr's Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 10
    hp: 80
    level: 7
    price: 0
    speed_penalty: 0
    traits:
      - rare
      - divine
      - intelligent
  Medusa's Scream:
    ac_bonus: 2
    bulk: 1
    hardness: 13
    hp: 52
    level: 13
    price: 300000
    speed_penalty: 0
    traits:
      - magical
  Medusa's Scream (Greater):
    ac_bonus: 2
    bulk: 1
    hardness: 15
    hp: 60
    level: 16
    price: 900000
    speed_penalty: 0
    traits:
      - magical
  Reflecting Shield:
    ac_bonus: 1
    bulk: 0.1
    hardness: 6
    hp: 24
    level: 18
    price: 1800000
    speed_penalty: 0
    traits:
      - uncommon
      - magical
  Spellguard Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 6
    hp: 24
    level: 6
    price: 25000
    speed_penalty: 0
    traits:
      - magical
  Spined Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 6
    hp: 24
    level: 7
    price: 36000
    speed_penalty: 0
    traits:
      - magical
  Steel Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 5
    hp: 20
    level: 0
    price: 200
    speed_penalty: 0
    traits: []
  Sturdy Shield (Greater):
    ac_bonus: 2
    bulk: 1
    hardness: 15
    hp: 120
    level: 13
    price: 300000
    speed_penalty: 0
    traits:
      - magical
  Sturdy Shield (Lesser):
    ac_bonus: 2
    bulk: 1
    hardness: 10
    hp: 80
    level: 7
    price: 36000
    speed_penalty: 0
    traits:
      - magical
  Sturdy Shield (Major):
    ac_bonus: 2
    bulk: 1
    hardness: 17
    hp: 136
    level: 16
    price: 1000000
    speed_penalty: 0
    traits:
      - magical
  Sturdy Shield (Minor):
    ac_bonus: 2
    bulk: 1
    hardness: 8
    hp: 64
    level: 4
    price: 10000
    speed_penalty: 0
    traits:
      - magical
  Sturdy Shield (Moderate):
    ac_bonus: 2
    bulk: 1
    hardness: 13
    hp: 104
    level: 10
    price: 100000
    speed_penalty: 0
    traits:
      - magical
  Sturdy Shield (Supreme):
    ac_bonus: 2
    bulk: 1
    hardness: 20
    hp: 160
    level: 19
    price: 4000000
    speed_penalty: 0
    traits:
      - magical
  Tower Shield:
    ac_bonus: 2
    bulk: 4
    hardness: 5
    hp: 20
    level: 0
    price: 1000
    speed_penalty: -5
    traits: []
  Wooden Shield:
    ac_bonus: 2
    bulk: 1
    hardness: 3
    hp: 12
    level: 0
    price: 100
    speed_penalty: 0
    traits: []