---
website:
  achievements:
    wiki_create:
      type: portal
      message: Created a wiki page.
    wiki_edit:
      type: portal
      message: Edited a wiki page.
  allow_html_in_markdown: true
  auto_wiki_export: true
  character_gallery_group: Region
  character_gallery_subgroup: ''
  hide_searchbox: true
  left_sidebar: false
  max_folder_size_kb: 2000
  max_upload_size_kb: 300
  permissions:
    manage_theme: Edit web portal CSS and colors.
    manage_wiki: Create and delete restricted wiki pages.
  restricted_pages:
  - home
  - policy:*
  - theme:*
  - mechanics:*
  - plots:*
  - organization:*
  - resource:*
  - rules:*
  shortcuts:
    wiki: website
    website/archive: website/export
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: Play
    menu:
    - title: Create a Character
      route: chargen
    - divider: true
    - title: Play
      route: play
    - title: Active Scenes
      route: scenes-live
    - title: Unshared Scenes
      route: scenes-unshared
    - title: Start New Scene
      route: scene-create
    - divider: true
    - title: Who's Online
      route: who
    - title: Forum
      route: forum
    - title: Mail
      route: mail
    - title: Events
      route: events
  - title: Directory
    menu:
    - title: Characters
      route: characters
    - title: Scenes
      route: scenes
    - title: Plots
      route: plots
    - divider: true
    - title: Players
      route: players
    - title: Game Admin
      route: admins
    - title: Census
      route: census
    - title: Locations
      route: locations
    - title: Combats
      route: combats
    - divider: true
    - title: Files
      route: files
  - title: Theme
    menu:
    - title: Theme Overview
      route: wiki-page
      id: theme
    - title: Theme FAQ
      route: wiki-page
      id: theme:theme-faq
    - divider: true
    - title: The World of Ea
      route: wiki-page
      id: theme:the_world_of_ea
    - title: Faiths & Gods
      route: wiki-page
      id: theme:deity
    - title: Cosmology & Planes
      route: wiki-page
      id: theme:cosmology-planes
    - title: Lands of Ea
      route: wiki-page
      id: theme:region
    - title: History & Timelines
      route: wiki-page
      id: theme:overview-timeline
    - title: Calendar of Ea
      route: wiki-page
      id: theme:calendar
    - title: Languages
      route: wiki-page
      id: theme:languages
    - title: Magic in Ea
      route: wiki-page
      id: theme:magic
    - divider: true
    - title: Slayers
      route: wiki-page
      id: theme:slayers
    - title: The Illuminators
      route: wiki-page
      id: theme:illuminators
    - title: The Shrike's Code
      route: wiki-page
      id: theme:shrikes_code
  - title: Mechanics
    menu:
    - title: Playtest Overview
      route: wiki-page
      id: playtest-overview
    - divider: true
    - title: Mechanics & Player Options
      route: wiki-page
      id: mechanics
    - title: Ancestries
      route: wiki-page
      id: mechanics:ancestry
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Limited Heritages
      route: wiki-page
      id: mechanics:limited-heritages
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Versatile Heritages
      route: wiki-page
      id: mechanics:versatile-heritages
    - title: Backgrounds
      route: wiki-page
      id: mechanics:backgrounds
    - title: Classes
      route: wiki-page
      id: mechanics:classes
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Class Feats
      route: wiki-page
      id: mechanics:class-feats
    - title: Archetypes & Dedications
      route: wiki-page
      id: mechanics:archetypes-dedications
    - title: Feats
      route: wiki-page
      id: mechanics:feats
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Ancestry Feats
      route: wiki-page
      id: mechanics:ancestry-feats
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> General Feats
      route: wiki-page
      id: mechanics:general-feats
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Skill Feats
      route: wiki-page
      id: mechanics:skill-feats
    - title: Skills
      route: wiki-page
      id: mechanics:skills
    - title: Equipment
      route: wiki-page
      id: mechanics:equipment
    - title: Spells
      route: wiki-page
      id: mechanics:spells
    - divider: true
    - title: House Rules & Clarifications
      route: wiki-page
      id: mechanics:house-rules
    - title: Alignment
      route: wiki-page
      id: mechanics:alignment
    - title: Hero Points
      route: wiki-page
      id: mechanics:hero_points
    - title: Roleplay Perks & Points (RPPs)
      route: wiki-page
      id: mechanics:rpp
    - divider: true
    - title: World Bestiary
      route: wiki-page
      id: mechanics:world-bestiary
    - title: Familiars
      route: wiki-page
      id: mechanics:familiar
    - title: Animal Companions
      route: wiki-page
      id: mechanics:animal-companions
    - title: Dragons
      route: wiki-page
      id: mechanics:dragons
    - divider: true
    - target: blank
      title: AON PRD <i class="fa fa-external-link-alt" aria-hidden="true">
      url: https://2e.aonprd.com/
  - title: Plots & Events
    menu:
    - title: Plots & Events Overview
      route: wiki-page
      id: plots
    - divider: true
    - title: Standard PRPs
      route: wiki-page
      id: plots:standard-prps
    - title: Death Consent PRPs
      route: wiki-page
      id: plots:dc-prps
    - title: Meetups
      route: wiki-page
      id: plots:meetups
    - title: Personal Story Plots
      route: wiki-page
      id: plots:personalstories
    - title: Plotmaster PRPs
      route: wiki-page
      id: plots:plotmaster-prps
    - title: Staffer Plots
      route: wiki-page
      id: plots:staffer-plots
  - title: Wiki
    menu:
    - title: Home
      route: wiki
    - title: Policies & Expectations
      route: wiki-page
      id: policy
    - title: Theme
      route: wiki-page
      id: theme
    - title: Mechanics & Player Options
      route: wiki-page
      id: mechanics
    - title: Organizations
      route: wiki-page
      id: organization
    - title: Plots & Events
      route: wiki-page
      id: plots
    - title: Resources
      route: wiki-page
      id: resource
    - divider: true
    - title: Create New Page
      route: wiki-create
    - title: All Pages
      route: wiki-all
    - title: Search Wiki
      route: search-wiki
    - title: Tags
      route: wiki-tags
    - title: Recent Changes
      route: recent-changes
    - divider: true
    - title: Files
      route: files
    - id: markdown
      title: Editing Help
      route: help-topic
  - title: Policies, Help, & Resources
    menu:
    - title: Requests
      route: jobs
    - title: Account
      route: account
    - divider: true
    - title: Game Help
      route: help
    - title: Search
      route: search-wiki
    - id: markdown
      title: Markdown Reference
      route: help-topic
    - title: Emoji Reference
      route: emoji
    - divider: true
    - title: Policies & Expectations
      route: wiki-page
      id: policy
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Terms of Service
      route: tos
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Game Policies
      route: wiki-page
      id: policy:game-policies
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Character Rules
        & Expectations
      route: wiki-page
      id: policy:character-rules
    - divider: true
    - title: Resources
      route: wiki-page
      id: resource
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Player Guide
      route: wiki-page
      id: resource:player-guide
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Writing a Prologue
      route: wiki-page
      id: resource:prologue
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> MUSHing 101 Tutorial
      route: wiki-page
      id: resource:mushing-101
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> AresMUSH Tips &
        Tricks
      route: wiki-page
      id: resource:ares-tips
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Glossary
      route: wiki-page
      id: resource:glossary
    - title: <i class="fas fa-caret-right" aria-hidden="true"></i> Ea Conversion Guide
      route: wiki-page
      id: resource:ea-conversion
  - title: Admin
    roles:
    - admin
    - coder
    menu:
    - title: Jobs
      route: jobs
    - title: Setup
      route: setup
    - title: Manage
      route: manage
    - title: Logs
      route: logs
    - title: Files
      route: files
    - title: Roles
      route: roles
    - title: Server
      route: server-info
    - title: Theme Colors
      route: setup-colors
    - title: Custom Styles
      route: textfile
      ids:
      - style
      - custom_style.scss
    - title: Home Page Text
      route: textfile
      ids:
      - text
      - website.txt
  - title: Code
    roles:
    - coder
    menu:
    - title: Tinker
      route: tinker
    - title: Custom Code
      route: custom-code
  - title: "<i class='fas fa-magnifying-glass'/>"
    menu:
    - title: Search Characters
      route: search-chars
    - title: Search Scenes
      route: search-scenes
    - title: Search Locations
      route: search-locations
    - title: Search Wiki
      route: search-wiki
    - title: Search Help
      route: search-help
    - title: Search Forum
      route: search-forum
    - title: Search Jobs/Requests
      route: search-jobs
  uploadable_extensions:
  - ".jpg"
  - ".png"
  - ".gif"
  - ".jpeg"
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: home
  wiki_export_cron:
    hour:
    - 3
    minute:
    - 37
  char_backup_cleanup_cron:
    hour:
    - 3
    minute:
    - 14
  public_wiki_folders:
  - misc
  default_public_folder: misc
